### ISSUE TITLE
Macros does not allow to use #load directives

### ISSUE THREAD

**Issue by clsource** [onyx-lang/onyx#173]
I don't know if this is a bug or a known behaviour.
Maybe for this is best to use with compiler extensions?.

> [!CAUTION]
> Macros are powerful meta-programming mechanisms that can be used in Onyx to extend the language. While using macros is not an anti-pattern in itself, this meta-programming mechanism should only be used when absolutely necessary.
> - See also: https://hexdocs.pm/elixir/macro-anti-patterns.html#unnecessary-macros

## Expected Behaviour

I want to use a `macro` that loads and use files.

## Sample Project

[macros.zip](https://github.com/user-attachments/files/17969751/macros.zip)

## Error code

```odin
requires :: [] {
    #load_all "lib"
    use lib
    #unquote lib.__using__()
}

main :: () {
    #unquote requires
}
```

**Comment by brendanfh** [comment]
This is by design. `#load`-ing files is "top-level" operation, meaning it can only occur in the outermost scope. Code-blocks are parsed as tho they are function bodies, since they currently can only be unquoted in function bodies. You can `use` in a function however, if you want to keep the use of the package to only a single block.

I normally don't worry too much about `#load` when I write Onyx. Typically I will just `#load_all "."` in my main file to load all other files and forget about it, treating it more like C#/Elixir/etc where an entire directory of files that all get loaded without thinking about it.

I see what you are going for here and it is definitely interesting. I will have to think about what it would look like to implement something like `__using__` for an Onyx package... :thinking:
