### ISSUE TITLE
Cli tool broken on windows 11

### ISSUE THREAD

**Issue by mfbulut** [onyx-lang/onyx#51]
I followed the steps at https://onyxlang.io/docs/install but
When I run onyx package init inside a empty folder I get an multiple errors

Unable to resolve symbol 'main'. Did you mean 'map'?
 101 |     #local MAIN_FUNCTION :: main.main

Expected this condition to be compile time known.
 135 |     #if (typeof MAIN_FUNCTION) == #type () -> void { // An error on this line means no 'main.main' was found in your program.

Package 'main' not found in included source files.
 100 |     use main

![image](https://github.com/onyx-lang/onyx/assets/51883559/39c70287-c43a-47f5-8cd7-c988c206f64e)

**Comment by brendanfh** [comment]
This was an huge oversight on my part, but I forgot to include the package manager in the Windows distribution of Onyx. This will be fixed in the next release, but for now there is a fix described in #38.

It boils down to manually creating the `tools` directory in your `ONYX_PATH`, and downloading the `onyx-pkg.onyx` file from [here](https://raw.githubusercontent.com/onyx-lang/onyx/master/scripts/onyx-pkg.onyx) and putting it in the new `tools` directory.

Hope this fixes the issue!
