### ISSUE TITLE
Tuple types aren't compile-time known..?

### ISSUE THREAD

**Issue by flysand7** [onyx-lang/onyx#89]
Trying to declare a custom iterator type that returns a tuple.

```
IT :: Iterator((i32, i32));
```

This leads to the error that this thing is not compile-time known.

I'm not sure if tuples are supposed to work, since the other piece of code did not produce an error:

```
/* ... */
        next = (data: rawptr) -> ((i32, i32), bool) {
        //                        ^^^^^^^^^^ me trying out to make a tuple type
            itr := cast(^Iterator_Ctx) data;
            if itr.idx == 10 {
                return -1, false;
            }
            itr.idx += 1;
            return (cast(i32) itr.r->int() itr.idx), true;
        },
```

**Comment by brendanfh** [comment]
Onyx does not really have "tuples" types at the moment. They only exist to support multiple return values, and should not be able to be nested. They are something to consider adding in the future, but for the moment a structure if preferred in that case. Or, use the `Pair` type from the core libraries (`Pair(i32, i32)`).

The error messages around what you are doing definitely need to be improved though, so that is what this issue will be tracking.

**Comment by brendanfh** [comment]
This kind of problem has been improved by not parsing "tuples" as types unless it is in the return type specifier of a procedure. This makes the code above actually give a parse error, because it is expecting a `->` after the `(i32, i32)` because it expects it to be a procedure.
