### ISSUE TITLE
On windows terminal (cmd.exe)  display by  "print" instruction is delayed

### ISSUE THREAD

**Issue by progamateur** [onyx-lang/onyx#91]
OS: Windows 10 /22H2/19045.3803
Onyx version : Release 0.1.8

In the following script :

    use core {*}
    main :: () {
	    println("Start ...");
 	    print("\tHello world! ");
	    os.sleep(5000);
	   println("\nEnd");
    }

"Hello world!" is not displayed immediately but after 5 seconds.
Is this normal?

P.S. same for WSL/Ubuntu

**Comment by brendanfh** [comment]
Yes this is the expected behavior, but it is a little confusing. The problem is that `printf` and `print` are buffered, so they don't immediately print things out to be a little more efficient. There is a special rule that says if the thing being printed ends with a new-line, it should be flush the output buffer to the screen. Since your "Hello, World!" does not have a new-line at the end, it is not being flushed before the sleep. To fix this, you can either add the new-line at the end, or manually call `__flush_stdio()` before sleeping.

```odin
use core {*}
main :: () {
    println("Start ...");
    print("\tHello world! ");
    __flush_stdio(); // Manually flush the print buffer
    os.sleep(5000);
    println("\nEnd");
}
```

**Comment by progamateur** [comment]
Thank you for your quick reply. The use of "__flush_stdio();" suits me because I need to use "print" to display on the same line an indication of processing progress, for example, as in the following script:


```
use core {*}

pr :: (s: str) {
	print(s);
	__flush_stdio();
}

main :: () {
	print("Processing start : ");
	for i: 1 .. 10 {
		pr(".");
		// do something
		os.sleep(500);
	}
	println("\nProcessing end");
}
```
